/* eslint-disable @typescript-eslint/no-unused-vars */

const GLOBAL_TRACKER = "global"

// Entry setup
const HORDE_ANY = [FACTION_NAME_ATTACK, FACTION_NAME_DEFEND, FACTION_NAME_OBSTACLE, FACTION_NAME_FROST]
const BASE_SIZE_ANY = [BASE_SIZE_SMALL, BASE_SIZE_MEDIUM, BASE_SIZE_LARGE]
const MOB_ALLIANCE_ANY = [MOB_ALLIANCE_NAME_ZOMBIE, MOB_ALLIANCE_NAME_SKELETON, MOB_ALLIANCE_NAME_CREEPER, MOB_ALLIANCE_NAME_SPIDER, MOB_ALLIANCE_NAME_SLIME, MOB_ALLIANCE_NAME_SILVERFISH]

// Trigger times
const TRIGGER_TIME_DAWN = "trigger_time_dawn"
const TRIGGER_TIME_DUSK = "trigger_time_dusk"
const TRIGGER_TIME_IMMEDIATE = "trigger_time_immediate"
const TRIGGER_TIME_AT_VILLAGE = "trigger_time_at_village"

// Snapshots
const SNAPSHOT_NOT_SET = -999
